### ISSUE TITLE
Embedded records mixin - embeddedSerializer.normalize is not a function

### ISSUE THREAD

**Issue by andyryan** [adopted-ember-addons/active-model-adapter#16]
I'm trying to use the embedded records mixin with all these new Ember-data changes. I finally have the new Active Model Adapter plugin but now I'm getting the error above when trying to use the EmbeddedRecordsMixin which worked fine before.

Anyone have a solution?

**Comment by pierrickrouxel** [comment]
I have the same problem

**Comment by fivetanley** [comment]
Hey there, we just pulled over CONTRIBUTING.md from the Ember Data core repository over here. Here's some stuff around filing issues: https://github.com/ember-data/active-model-adapter/blob/master/CONTRIBUTING.md#reporting-a-bug

There's a link to JSBIN in there with the ActiveModelAdapter preconfigured. Otherwise if you could give us some demo code with the model definition, serializer definition, and example payload, that would help us track that down. Thanks!

**Comment by jherdman** [comment]
Hi friends. Is this still an issue?
